name: advection-docs
channels:
  - conda-forge
dependencies:
  - docutils<0.18
  - fontconfig
  - freetype
  - gdal
  - graphviz
  - h5py
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - numpydoc
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - scipy
  - sphinx
  - sphinx-argparse
  - sphinx_rtd_theme
  - texlive-core
  - pip:
    - git+https://github.com/tsutterley/pyTMD.git
    - git+https://github.com/smithb/pointCollection.git
    - ..
